version: "3"
services:
  web:
    image: 192.168.99.100:55000/ftadverts/api:ci-${API_BUILD_NUMBER-1}
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "5000:80"
    networks:
      - webnet
    environment:
      - TEAMCITY_PROJECT_NAME	  
networks:
  webnet: